### ISSUE TITLE
Kotlin 1.9.x support

### ISSUE THREAD

**Issue by rocketraman** [bnorm/kotlin-power-assert#104]
Kotlin-power-assert seems to work with 1.9.x, and even the sample uses 1.9.x, but the README does not list it as supported. Can official support be added for it?

I do note this statement, but given that every previous version of Kotlin is listed, its easy to miss, or to assume the plugin has not been updated:

> If a version of Kotlin or this plugin is not listed it can be assumed to maintain compatibility with the next oldest version listed.

**Comment by bnorm** [comment]
Yes, Kotlin 1.9.x is supported by 0.13.0. (Though I think there is a small incompatibility if an error needs to be reported, so I might need to release a new version)

The compatibility guide is not the easiest thing to make clear, so if you have any ideas on how to improve the README, let me know! Maybe I should make the Kotlin versions a range?

**Comment by rocketraman** [comment]
> Maybe I should make the Kotlin versions a range?

That seems reasonable.

**Comment by TWiStErRob** [comment]
I've always found these helpful, although I also found them too implicit. So ++ on version ranges.

* https://developer.android.com/build/releases/gradle-plugin#updating-gradle
* https://developer.android.com/build/releases/gradle-plugin#android_gradle_plugin_and_android_studio_compatibility
* https://docs.gradle.org/current/userguide/compatibility.html

I'm also having "fun" trying to maintain a 3D compatibility matrix and found ranges very useful: https://github.com/TWiStErRob/net.twisterrob.gradle

**Comment by AlexTrotsenko** [comment]
@bnorm similar question about  Kotlin v2.0 -  is current version of the plug is expected to work with it well?

**Comment by bnorm** [comment]
Support for this plugin, starting with Kotlin 2.0.0, has moved into the Kotlin repository! Part of that move was to make it compatible with Kotlin 2.0 and update the artifact coordinates to align with other official compiler plugins. Everyone should migrate to the official compiler plugin (the documentation you linked) when upgrading to Kotlin 2.0.

This repository/plugin will not be updated to support Kotlin 2.0. I will be releasing a new version which fails Gradle builds and indicates as much in the failure message. I'm hoping to release this version soon and will also provide some documentation in the release notes/README about migrating.

**Comment by AlexTrotsenko** [comment]
@bnorm  thank you very much for your quick and detailed reply and all your efforts in making this ~excellent~ powerful assert project!

**Comment by rocketraman** [comment]
> Support for this plugin, starting with Kotlin 2.0.0, has moved into the Kotlin repository!

Very cool! Congrats.
