### ISSUE TITLE
Support Kotlin multiplatform

### ISSUE THREAD

**Issue by bnorm** [bnorm/kotlin-power-assert#5]
High-jacking of the `assert` function in Kotlin/JVM is fine for now, but this function does not exist on Kotlin/JS. It might be best to introduce a new - library specific - function which exists on all platforms.

**Comment by JakeWharton** [comment]
Can you use the first-party `kotlin.test` APIs? They're a bit higher level (`assertTrue`, `assertEquals`, etc.).

https://github.com/JetBrains/kotlin/tree/master/libraries/kotlin.test

**Comment by bnorm** [comment]
That's an interesting idea; certainly possible. Right now I inline the construction and throwing of the AssertionError which might not play well with `kotlin.test` and it's use of the `Asserter` instance.

But I'm open to any ideas. Right now I'm just focusing on better understanding the IR structure produced and how it can be transformed.
