### ISSUE TITLE
Kotest assertions support

### ISSUE THREAD

**Issue by sergeidyga** [bnorm/kotlin-power-assert#65]
Hi! Thanks for the awesome plugin!

Is Kotest assertions support planned somewhere in the future?

**Comment by sschuberth** [comment]
If I may chime in here as another Kotest user: Currently, Kotest's output when asserting equality of data classes (which may contain other data classes) is quite limited. Basically, it just asserts that the `toString()` representations of the classes are equal. As a result, the message for a failed assertion is long an rather non-telling.

So it would be nice to be able to leverage `kotlin-power-assert` for writing a Kotest matcher that is able to print some nice diagram about the differences in a hierarchy of nested data classes. In particular, equal data classes in the hierarchy should be skipped to not clutter the assertion output with unnecessary stuff.

**Comment by bnorm** [comment]
Functions with receivers (infix or not) are supported (#68), so all Kotest would need to do is add overloads which also take a string as the last parameter. Then kotlin-power-assert could transform Kotest assertions. See the [tests here](https://github.com/bnorm/kotlin-power-assert/blob/master/kotlin-power-assert-plugin/src/test/kotlin/com/bnorm/power/InfixFunctionTest.kt) for an example. Explicit support of Kotest is not within the scope of this plugin, so closing as "not planned".

As for the data class example, I think that falls under #76, as we could diff data classes intelligently if we new their equals function wasn't custom.
