### ISSUE TITLE
Support for assert functions with receivers/infix functions?

### ISSUE THREAD

**Issue by LewsTherinTelescope** [bnorm/kotlin-power-assert#68]
To elaborate on the title, I like to have a function like the following for testing:

```kotlin
infix fun <V> V.mustEqual(expected: V): Unit = assertEquals(expected, this)
```

Which allows writing test functions in what to me is a bit more of a natural way:

```kotlin
@Test fun testAddition() {
	1 + 1 mustEqual 2
}
```

I wanted to use it with this plugin, so I tried adding it to the list of functions to transform and implementing an overload with a message parameter as follows:

```kotlin
fun <V> V.mustEqual(expected: V, message: () -> String): Unit =
	assertEquals(expected, this, message())
```

However, it appears that this does not work (neither in infix mode nor "dot mode"). It _does_ work fine if I instead take both values as normal parameters:

```kotlin
fun <V> mustEqual(actual: V, expected: V): Unit = assertEquals(expected, this)
fun <V> mustEqual(actual: V, expected: V, message: () -> String): Unit =
	assertEquals(expected, actual, message())
```

Which leads me to believe that the issue is how it uses a receiver for one of the parameters, since changing only that does fix it. 

Obviously, I could just use `assertEquals`, and will be doing exactly that for now because this plugin is definitely worth that very minor (and subjective) stylistic inconvenience, but figured I'd bring it up, in case it's not too time-consuming to add support for.

(It seems to me like #65 may be related to this, but having not used Kotest, I'm not sure.)

**Comment by bnorm** [comment]
Yeah, I'll definitely take a look at this. The `expected` parameter of the infix `mustEqual` will to be diagramed but in your example it is a constant so nothing needs to be diagramed. If you try something like `2 mustEqual 1 + 2` you should see what I mean.

The receiver on the other hand I know is not included in the diagram right now so I can take a look at that.

**Comment by LewsTherinTelescope** [comment]
Just tested your suggestion and yeah you're totally right, the parameter is diagrammed fine when it's more complex than just a constant number, which none of my failing quick checks were. Thanks for pointing that out!

**Comment by knizamov** [comment]
That would indeed be very handy for Kotest assertions, as for now to print the whole object or some additional context, one needs to explicitly use [Clues](https://kotest.io/docs/assertions/clues.html) which bring quite a bit of boilerplate as otherwise the assertion like that `user.name shouldNotBe null` would just report `<null> should not equal <null>` if user object was null and the context (user) nor the state is unclear.
There is even an issue for this https://github.com/kotest/kotest/issues/2241 and the author event did some experiment but has never finished.
