### ISSUE TITLE
Release a new version with new changes

### ISSUE THREAD

**Issue by knizamov** [bnorm/kotlin-power-assert#78]
Hi. Sorry to bother you.
Could you please release a new version? Would love to try out infix based assertions.

**Comment by bnorm** [comment]
Apologize for it being so long between releases; life has kept me busy elsewhere. But I'm hopeful I can publish a release soon after a few more bug fixes: #77 and #80.

**Comment by christophsturm** [comment]
you could put out an release with the current fixes , then make it work with 1.8.20 and do another release. then people who use older kotlin also have a release that has the new features.

**Comment by bnorm** [comment]
> you could put out an release with the current fixes , then make it work with 1.8.20 and do another release.

That's a good idea. I'll plan to release both a 0.12.1 with recent fixes and a 0.13.0 with 1.8.20 support. Hope to get that done before KotlinConf!

**Comment by bnorm** [comment]
Version 0.12.1 was just published!
